### ISSUE TITLE
Pyo on Windows 10

### ISSUE THREAD

**Issue by mehulsuresh** [belangeo/pyo#159]
Pyo crashes python on s = Server().boot() on windows whenever a midi input device is connected. Also displays no error messages. Works perfectly fine on Ubuntu 18.04.  Also it is unable to use asio host api. The only api that seems to be working is mme, which however crashes whenever there is a midi input

`* Checking for any available audio input... *
* Checking audio output hosts... *
* Testing mme... *
* Testing directsound... *
* Testing asio... *
Pyo can't find audio host 'asio'. Currently available hosts are:
    apis:
    mme
    windows directsound
    windows wasapi
    windows wdm-ks

* Testing wasapi... *
Portaudio error in Pa_OpenStream: Invalid device
Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
* Testing wdm-ks... *

Results
-------

Duplex mode OK!
Initialize the Server with duplex=1 as argument.

Host: mme  ==>  OK!
Host: directsound  ==>  OK!
Host: asio  ==>  OK!
Host: wasapi  ==>  Failed...
Host: wdm-ks  ==>  OK!
Initialize the Server with the desired host given to winhost argument.

Finished!`

Let me know if you need any more info. Any help you can provide to fix this is greatly appreciated. Thanks :)

**Comment by belangeo** [comment]
> Pyo crashes python on s = Server().boot() on windows whenever a midi input device is connected. 

What is the output of `pm_list_devices()` ?

> Also it is unable to use asio host api.

What is the output of `pa_list_devices()` ?

> The only api that seems to be working is mme ...

The most reliable audio host on windows still seems to be directsound. For sure, you don't want to use mme no more and WASAPI needs to be carefully tuned to be effective.

[http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html#tunning-the-windows-wasapi-driver](http://ajaxsoundstudio.com/pyodoc/winaudioinspect.html#tunning-the-windows-wasapi-driver)

**Comment by mehulsuresh** [comment]
> What is the output of `pm_list_devices()` ?
>>> pm_list_devices()
MIDI devices:
0: OUT, name: Microsoft MIDI Mapper, interface: MMSystem
1: IN, name: Boutique, interface: MMSystem
2: IN, name: Focusrite USB MIDI, interface: MMSystem
3: OUT, name: Microsoft GS Wavetable Synth, interface: MMSystem
4: OUT, name: Boutique, interface: MMSystem
5: OUT, name: Focusrite USB MIDI, interface: MMSystem
> What is the output of `pa_list_devices()` ?
>>> pa_list_devices()
AUDIO devices:
0: IN, name: Microsoft Sound Mapper - Input, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
1: IN, name: IN (Boutique), host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
2: IN, name: Focusrite USB (Focusrite USB Au, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
3: IN, name: Microphone (Logitech Webcam C93, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
4: IN, name: Microphone (Realtek High Defini, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
5: IN, name: Microphone (Rift Audio), host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
6: OUT, name: Microsoft Sound Mapper - Output, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
7: OUT, name: OUT (Boutique), host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
8: OUT, name: Speaker/Headphone (Realtek High, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
9: OUT, name: Focusrite USB (Focusrite USB Au, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
10: OUT, name: Realtek Digital Output (Realtek, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
11: OUT, name: Headphones (Rift Audio), host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
12: OUT, name: U28E590 (NVIDIA High Definition, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
13: OUT, name: U28E590 (NVIDIA High Definition, host api index: 0, default sr: 44100 Hz, latency: 0.090000 s
14: IN, name: Primary Sound Capture Driver, host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
15: IN, name: IN (Boutique), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
16: IN, name: Focusrite USB (Focusrite USB Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
17: IN, name: Microphone (Logitech Webcam C930e), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
18: IN, name: Microphone (Realtek High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
19: IN, name: Microphone (Rift Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
20: OUT, name: Primary Sound Driver, host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
21: OUT, name: OUT (Boutique), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
22: OUT, name: Speaker/Headphone (Realtek High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
23: OUT, name: Focusrite USB (Focusrite USB Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
24: OUT, name: Realtek Digital Output (Realtek High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
25: OUT, name: Headphones (Rift Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
26: OUT, name: U28E590 (NVIDIA High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
27: OUT, name: U28E590 (NVIDIA High Definition Audio), host api index: 1, default sr: 44100 Hz, latency: 0.120000 s
28: OUT, name: Speaker/Headphone (Realtek High Definition Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
29: OUT, name: OUT (Boutique), host api index: 2, default sr: 44100 Hz, latency: 0.003000 s
30: OUT, name: Focusrite USB (Focusrite USB Audio), host api index: 2, default sr: 44100 Hz, latency: 0.003000 s
31: OUT, name: Realtek Digital Output (Realtek High Definition Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
32: OUT, name: Headphones (Rift Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
33: OUT, name: U28E590 (NVIDIA High Definition Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
34: OUT, name: U28E590 (NVIDIA High Definition Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
35: IN, name: Focusrite USB (Focusrite USB Audio), host api index: 2, default sr: 44100 Hz, latency: 0.003000 s
36: IN, name: Microphone (Logitech Webcam C930e), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
37: IN, name: Microphone (Realtek High Definition Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
38: IN, name: IN (Boutique), host api index: 2, default sr: 44100 Hz, latency: 0.003000 s
39: IN, name: Microphone (Rift Audio), host api index: 2, default sr: 48000 Hz, latency: 0.003000 s
40: OUT, name: Speakers (Realtek HD Audio output), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
41: IN, name: Line In (Realtek HD Audio Line input), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
42: IN, name: Stereo Mix (Realtek HD Audio Stereo input), host api index: 3, default sr: 48000 Hz, latency: 0.010000 s
43: IN, name: Microphone (Realtek HD Audio Mic input), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
44: OUT, name: SPDIF Out (Realtek HDA SPDIF Out), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
45: OUT, name: Line Out (OUT (Boutique)), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
46: IN, name: IN (IN (Boutique)), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
47: IN, name: Microphone (Logitech Webcam C930e), host api index: 3, default sr: 48000 Hz, latency: 0.010000 s
48: OUT, name: Headphones (Headphone), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
49: IN, name: Microphone (MicIn), host api index: 3, default sr: 48000 Hz, latency: 0.010000 s
50: OUT, name: Output (NVIDIA High Definition Audio), host api index: 3, default sr: 48000 Hz, latency: 0.010000 s
51: OUT, name: Output (NVIDIA High Definition Audio), host api index: 3, default sr: 48000 Hz, latency: 0.010000 s
52: IN, name: Focusrite USB (fniusbwave_44), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
53: OUT, name: Analog Out (fniusbwave_44), host api index: 3, default sr: 44100 Hz, latency: 0.010000 s
54: OUT, name: Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(WH-CH700N)), host api index: 3, default sr: 8000 Hz, latency: 0.010000 s
55: IN, name: Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(WH-CH700N)), host api index: 3, default sr: 8000 Hz, latency: 0.010000 s

**Comment by belangeo** [comment]
Wow, there is a lot of devices connected..! I guess you should start by trying to unplug the external devices one by one to see which one is causing trouble.

**Comment by mehulsuresh** [comment]
Okay so the one causing the issue is the boutique midi synth and keyboard. Tried to connect a focusrite soundcard and plug the midi synth using a midi cable to the soundcard but it still causes a problem. Also tried to disconnect everything and just connect a midi keyboard via usb and server still doesnt boot. also tried on another win10 system same issue. As long as there is no midi input everything works fine. otherwise python just crashes with no error message

**Comment by amerizalde** [comment]
I am having the same issue with my MIDI controller. It is an Oxygen25. The server will crash at the .boot() call using any of the MIDI examples if the MIDI controller is powered on. If the controller is powered off, the server will boot, and will not crash if you turn the controller on after, but will ignore the controller since it is already booted. Running .reinit() with the controller on will crash the server.
I also tried .allowMicrosoftMidiDevices() with and without the controller powered on before .boot(), but the server crashes on both.

**Comment by robertmielewczyk** [comment]
**I'm having the same issue when:**
- I have my MIDI controller plugged in
- I run Server(midi='pm') or Server(midi='portmidi')

**The workaround I found is to** 
run Server(midi='jack')

**Comment by belangeo** [comment]
Can someone try this installer and report back here if everything is fine? Portmidi has been fixed upstream. Thanks!

https://www.dropbox.com/s/4w4z4av64fvpsq2/pyo-1.0.1-cp36-cp36m-win_amd64.whl?dl=0

https://www.dropbox.com/s/s2d8ox6qvdwnqq8/pyo-1.0.1-cp37-cp37m-win_amd64.whl?dl=0

https://www.dropbox.com/s/1bfw8xcqbndzx5b/pyo-1.0.1-cp38-cp38-win_amd64.whl?dl=0

**Comment by ultrasound1372** [comment]
Is this fixed? This issue is still open.

**Comment by Lottie99** [comment]
Just a few hours ago I’ve tried to connect my midi keyboard to pyo using windows 10. Is still the same: the code crashes without a message of error and doesn’t work. If I unplug the usb of the midi device, everything work! The code crash also if I comment the SetMidiInputDevice() command and the usb is plugged in the pc

**Comment by belangeo** [comment]
> Is this fixed? This issue is still open.

Fixed with 1.0.3. Didn't get any feedback since...

**Comment by belangeo** [comment]
> Just a few hours ago I’ve tried to connect my midi keyboard to pyo using windows 10. Is still the same: the code crashes without a message of error and doesn’t work. If I unplug the usb of the midi device, everything work! The code crash also if I comment the SetMidiInputDevice() command and the usb is plugged in the pc

What is the output of :

pm_list_devices()

and which index do you give to 

Server.setMidiInputDevice()

**Comment by Lottie99** [comment]
> > Just a few hours ago I’ve tried to connect my midi keyboard to pyo using windows 10. Is still the same: the code crashes without a message of error and doesn’t work. If I unplug the usb of the midi device, everything work! The code crash also if I comment the SetMidiInputDevice() command and the usb is plugged in the pc
> 
> What is the output of :
> 
> pm_list_devices()
> 
> and which index do you give to
> 
> Server.setMidiInputDevice()

The output of pm_list_devices() is 2 for the midi keyboard. I’ve set the index to 2 and to 99 and it still doesn’t work...

**Comment by rubenmedrano** [comment]
I am having the same issue with Pyo 1.0.3.
No ASIO!

**Comment by belangeo** [comment]
@rubenmedrano Just to be sure... Is ASIO4ALL installed on the system?

**Comment by rubenmedrano** [comment]
No, no ASIO4ALL installed. 
Normally use the original RME ASIO drivers that my audio interface has. And a few years ago I was able to useit with Pyo (but with Python 2.7).
Now I am using Python 3.8

**Comment by belangeo** [comment]
Right, I switched to MSYS2 portaudio package, and indeed, it does not support ASIO out-of-the-box. For the next release, I plan to update the build routine on Windows to use vcpkg (I'm already using it for portmidi) for all dependencies. I'll make sure that ASIO is supported again.

**Comment by dsholes** [comment]
I think this is related to a latency issue I'm having (#198), but just wondering what the timeline for the next release is that supports ASIO? If you could point me in the right direction, I can take a look and see if I'm able to help update the build routine.

**Comment by belangeo** [comment]
The job is done. I have a few more fixes I want to do before the next release, but it should be pretty soon (within a month I'd say).

**Comment by rubenmedrano** [comment]
That's great news! Thanks!

**Comment by belangeo** [comment]
ASIO support is back in version 1.0.4.
